// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adeqxcjnajawbpwmrfqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZXF4Y2puYWphd2Jwd21yZnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDMyNzUsImV4cCI6MjA2OTM3OTI3NX0.SkZh3CiN8jU8QeAyU_TWbTVsYlmdYDcqk3XvUa8OwrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});